country_code_dict = {
    'FJ': {'en': 'Fiji', 'zh': '斐济'},
    'SL': {'en': 'Sierra Leone', 'zh': '塞拉利昂'},
    'PT': {'en': 'Portugal', 'zh': '葡萄牙'},
    'BF': {'en': 'Burkina Faso', 'zh': '布基纳法索'},
    'TT': {'en': 'Trinidad and Tobago', 'zh': '特立尼达和多巴哥'},
    'AS': {'en': 'American Samoa', 'zh': '美属萨摩亚'},
    'AI': {'en': 'Anguilla', 'zh': '安圭拉'},
    'GD': {'en': 'Grenada', 'zh': '格林纳达'},
    'RU': {'en': 'Russia', 'zh': '俄罗斯'},
    'BV': {'en': 'Bouvet Island', 'zh': '布维特岛'},
    'IQ': {'en': 'Iraq', 'zh': '伊拉克'},
    'OM': {'en': 'Oman', 'zh': '阿曼'},
    'BL': {'en': 'Saint Barthelemy', 'zh': '圣巴泰勒米岛'},
    'MP': {'en': 'Northern Mariana Islands', 'zh': '北马里亚纳群岛'},
    'GF': {'en': 'French Guiana', 'zh': '法属圭亚那'},
    'BQ': {'en': 'Nederland Caribbean', 'zh': '荷兰加勒比'},
    'JO': {'en': 'Jordan', 'zh': '约旦'},
    'PG': {'en': 'Papua New Guinea', 'zh': '巴布亚新几内亚'},
    'LR': {'en': 'Liberia', 'zh': '利比里亚'},
    'MC': {'en': 'Monaco', 'zh': '摩纳哥'},
    'KZ': {'en': 'Kazakhstan', 'zh': '哈萨克斯坦'},
    'LK': {'en': 'Sri Lanka', 'zh': '斯里兰卡'},
    'KW': {'en': 'Kuwait', 'zh': '科威特'},
    'KE': {'en': 'Kenya', 'zh': '肯尼亚'},
    'FK': {'en': 'Falkland Islands', 'zh': '福克兰群岛'},
    'LU': {'en': 'Luxembourg', 'zh': '卢森堡'},
    'DM': {'en': 'Dominica', 'zh': '多米尼克'},
    'BN': {'en': 'Brunei Darussalam', 'zh': '文莱'},
    'TV': {'en': 'Tuvalu', 'zh': '图瓦卢'},
    'ER': {'en': 'Eritrea', 'zh': '厄立特里亚'},
    'ET': {'en': 'Ethiopia', 'zh': '埃塞俄比亚'},
    'NG': {'en': 'Nigeria', 'zh': '尼日利亚'},
    'MM': {'en': 'Myanmar', 'zh': '缅甸'},
    'TN': {'en': 'Tunisia', 'zh': '突尼斯'},
    'IM': {'en': 'Isle of Man', 'zh': '马恩岛'},
    'VN': {'en': 'Viet Nam', 'zh': '越南'},
    'PM': {'en': 'Saint Pierre and Miquelon', 'zh': '圣皮埃尔和密克隆群岛'},
    'IT': {'en': 'Italy', 'zh': '意大利'},
    'AR': {'en': 'Argentina', 'zh': '阿根廷'},
    'BE': {'en': 'Belgium', 'zh': '比利时'},
    'FI': {'en': 'Finland', 'zh': '芬兰'},
    'MD': {'en': 'Moldova', 'zh': '摩尔多瓦'},
    'TO': {'en': 'Tonga', 'zh': '汤加'},
    'PR': {'en': 'Puerto Rico', 'zh': '波多黎各'},
    'HU': {'en': 'Hungary', 'zh': '匈牙利'},
    'VU': {'en': 'Vanuatu', 'zh': '瓦努阿图'},
    'NP': {'en': 'Nepal', 'zh': '尼泊尔'},
    'KI': {'en': 'Kiribati', 'zh': '基里巴斯'},
    'LC': {'en': 'Saint Lucia', 'zh': '圣卢西亚'},
    'FM': {'en': 'Micronesia', 'zh': '密克罗尼西亚联邦'},
    'SJ': {'en': 'Svalbard and Jan Mayen', 'zh': '斯瓦尔巴特和扬马延'},
    'LT': {'en': 'Lithuania', 'zh': '立陶宛'},
    'AG': {'en': 'Antigua and Barbuda', 'zh': '安提瓜和巴布达'},
    'GY': {'en': 'Guyana', 'zh': '圭亚那'},
    'MA': {'en': 'Morocco', 'zh': '摩洛哥'},
    'AO': {'en': 'Angola', 'zh': '安哥拉'},
    'DJ': {'en': 'Djibouti', 'zh': '吉布提'},
    'TL': {'en': 'East Timor', 'zh': '东帝汶'},
    'TK': {'en': 'Tokelau', 'zh': '托克劳'},
    'EE': {'en': 'Estonia', 'zh': '爱沙尼亚'},
    'SA': {'en': 'Saudi Arabia', 'zh': '沙特阿拉伯'},
    'NA': {'en': 'Namibia', 'zh': '纳米比亚'},
    'BW': {'en': 'Botswana', 'zh': '博茨瓦纳'},
    'ML': {'en': 'Mali', 'zh': '马里'},
    'GU': {'en': 'Guam', 'zh': '关岛'},
    'SG': {'en': 'Singapore', 'zh': '新加坡'},
    'CY': {'en': 'Cyprus', 'zh': '塞浦路斯'},
    'AX': {'en': 'Aland Islands', 'zh': '奥兰群岛'},
    'XK': {'en': 'The Republic of Kosovo', 'zh': '科索沃'},
    'GG': {'en': 'Guernsey', 'zh': '根西岛'},
    'NC': {'en': 'New Caledonia', 'zh': '新喀里多尼亚'},
    'EC': {'en': 'Ecuador', 'zh': '厄瓜多尔'},
    'SD': {'en': 'Sudan', 'zh': '苏丹'},
    'GN': {'en': 'Guinea', 'zh': '几内亚'},
    'DO': {'en': 'Dominican Republic', 'zh': '多米尼加共和国'},
    'NZ': {'en': 'New Zealand', 'zh': '新西兰'},
    'MS': {'en': 'Montserrat', 'zh': '蒙塞拉特群岛'},
    'IN': {'en': 'India', 'zh': '印度'},
    'BS': {'en': 'Bahamas', 'zh': '巴哈马'},
    'AE': {'en': 'United Arab Emirates', 'zh': '阿拉伯联合酋长国'},
    'RW': {'en': 'Rwanda', 'zh': '卢旺达'},
    'ID': {'en': 'Indonesia', 'zh': '印度尼西亚'},
    'CD': {'en': 'Democratic Republic of Congo', 'zh': '刚果民主共和国'},
    'HR': {'en': 'Croatia', 'zh': '克罗地亚'},
    'CU': {'en': 'Cuba', 'zh': '古巴'},
    'NF': {'en': 'Norfolk Island', 'zh': '诺福克岛'},
    'NR': {'en': 'Nauru', 'zh': '瑙鲁'},
    'TC': {'en': 'Turks and Caicos Islands', 'zh': '特克斯和凯科斯群岛'},
    'MY': {'en': 'Malaysia', 'zh': '马来西亚'},
    'CX': {'en': 'Christmas Island', 'zh': '圣诞岛'},
    'SO': {'en': 'Somalia', 'zh': '索马里'},
    'YE': {'en': 'Yemen', 'zh': '也门'},
    'BG': {'en': 'Bulgaria', 'zh': '保加利亚'},
    'JP': {'en': 'Japan', 'zh': '日本'},
    'UA': {'en': 'Ukraine', 'zh': '乌克兰'},
    'MU': {'en': 'Mauritius', 'zh': '毛里求斯'},
    'AF': {'en': 'Afghanistan', 'zh': '阿富汗'},
    'ZW': {'en': 'Zimbabwe', 'zh': '津巴布韦'},
    'NU': {'en': 'Niue', 'zh': '纽埃'},
    'JE': {'en': 'Jersey', 'zh': '泽西岛'},
    'PW': {'en': 'Palau', 'zh': '帕劳'},
    'ME': {'en': 'Montenegro', 'zh': '黑山'},
    'EG': {'en': 'Egypt', 'zh': '埃及'},
    'ZM': {'en': 'Zambia', 'zh': '赞比亚'},
    'TD': {'en': 'Chad', 'zh': '乍得'},
    'SN': {'en': 'Senegal', 'zh': '塞内加尔'},
    'TG': {'en': 'Togo', 'zh': '多哥'},
    'SS': {'en': 'South Sudan', 'zh': '南苏丹'},
    'SR': {'en': 'Suriname', 'zh': '苏里南'},
    'NL': {'en': 'The Netherlands', 'zh': '荷兰'},
    'NE': {'en': 'Niger', 'zh': '尼日尔'},
    'GI': {'en': 'Gibraltar', 'zh': '直布罗陀'},
    'BZ': {'en': 'Belize', 'zh': '伯利兹'},
    'GW': {'en': 'Guinea-Bissau', 'zh': '几内亚比绍'},
    'SX': {'en': 'Sint Maarten', 'zh': '圣马丁岛'},
    'KN': {'en': 'Saint Kitts and Nevis', 'zh': '圣基茨和尼维斯'},
    'GP': {'en': 'Guadeloupe', 'zh': '瓜德罗普'},
    'CA': {'en': 'Canada', 'zh': '加拿大'},
    'BO': {'en': 'Bolivia', 'zh': '玻利维亚'},
    'AT': {'en': 'Austria', 'zh': '奥地利'},
    'CL': {'en': 'Chile', 'zh': '智利'},
    'CK': {'en': 'Cook Islands', 'zh': '库克群岛'},
    'GT': {'en': 'Guatemala', 'zh': '危地马拉'},
    'MG': {'en': 'Madagascar', 'zh': '马达加斯加'},
    'UY': {'en': 'Uruguay', 'zh': '乌拉圭'},
    'DE': {'en': 'Germany', 'zh': '德国'},
    'DZ': {'en': 'Algeria', 'zh': '阿尔及利亚'},
    'LV': {'en': 'Latvia', 'zh': '拉脱维亚'},
    'IR': {'en': 'Iran', 'zh': '伊朗'},
    'SM': {'en': 'San Marino', 'zh': '圣马力诺'},
    'HM': {'en': 'Heard Island and McDonald Islands', 'zh': '赫德与麦克唐纳群岛'},
    'MX': {'en': 'Mexico', 'zh': '墨西哥'},
    'IE': {'en': 'Ireland', 'zh': '爱尔兰'},
    'GL': {'en': 'Greenland', 'zh': '格陵兰'},
    'RO': {'en': 'Romania', 'zh': '罗马尼亚'},
    'AQ': {'en': 'Antarctica', 'zh': '南极洲'},
    'SY': {'en': 'Syria', 'zh': '叙利亚'},
    'MT': {'en': 'Malta', 'zh': '马耳他'},
    'TR': {'en': 'Turkey', 'zh': '土耳其'},
    'TH': {'en': 'Thailand', 'zh': '泰国'},
    'MW': {'en': 'Malawi', 'zh': '马拉维'},
    'ZA': {'en': 'South Africa', 'zh': '南非'},
    'MF': {'en': 'French Saint Martin', 'zh': '法属圣马丁'},
    'CG': {'en': 'Republic of the Congo', 'zh': '刚果共和国'},
    'MK': {'en': 'Macedonia', 'zh': '马其顿'},
    'PL': {'en': 'Poland', 'zh': '波兰'},
    'VA': {'en': 'Vatican', 'zh': '梵蒂冈'},
    'MV': {'en': 'Maldives', 'zh': '马尔代夫'},
    'BB': {'en': 'Barbados', 'zh': '巴巴多斯'},
    'PN': {'en': 'Pitcairn Islands', 'zh': '皮特凯恩群岛'},
    'US': {'en': 'United States', 'zh': '美国'},
    'KM': {'en': 'Comoros', 'zh': '科摩罗'},
    'AU': {'en': 'Australia', 'zh': '澳大利亚'},
    'CN': {'en': 'China', 'zh': '中国'},
    'GR': {'en': 'Greece', 'zh': '希腊'},
    'UZ': {'en': 'Uzbekistan', 'zh': '乌兹别克斯坦'},
    'AL': {'en': 'Albania', 'zh': '阿尔巴尼亚'},
    'KG': {'en': 'Kyrgyzstan', 'zh': '吉尔吉斯斯坦'},
    'LS': {'en': 'Lesotho', 'zh': '莱索托'},
    'SK': {'en': 'Slovakia', 'zh': '斯洛伐克'},
    'MZ': {'en': 'Mozambique', 'zh': '莫桑比克'},
    'SC': {'en': 'Seychelles', 'zh': '塞舌尔'},
    'MH': {'en': 'Marshall Islands', 'zh': '马绍尔群岛'},
    'ST': {'en': 'Sao Tome and Principe', 'zh': '圣多美和普林西比'},
    'HN': {'en': 'Honduras', 'zh': '洪都拉斯'},
    'PS': {'en': 'Palestine', 'zh': '巴勒斯坦'},
    'WF': {'en': 'Wallis and Futuna', 'zh': '瓦利斯和富图纳群岛'},
    'BI': {'en': 'Burundi', 'zh': '布隆迪'},
    'KR': {'en': 'Republic of Korea', 'zh': '韩国'},
    'LY': {'en': 'Libya', 'zh': '阿拉伯利比亚民众国'},
    'LI': {'en': 'Liechtenstein', 'zh': '列支敦士登'},
    'CZ': {'en': 'Czech', 'zh': '捷克'},
    'BT': {'en': 'Bhutan', 'zh': '不丹'},
    'CI': {'en': 'Ivory Coast', 'zh': '科特迪瓦'},
    'BD': {'en': 'Bangladesh', 'zh': '孟加拉'},
    'CF': {'en': 'Central African Republic', 'zh': '中非'},
    'GQ': {'en': 'Equatorial Guinea', 'zh': '赤道几内亚'},
    'TJ': {'en': 'Tajikistan', 'zh': '塔吉克斯坦'},
    'LB': {'en': 'Lebanon', 'zh': '黎巴嫩'},
    'AZ': {'en': 'Azerbaijan', 'zh': '阿塞拜疆'},
    'BR': {'en': 'Brazil', 'zh': '巴西'},
    'PK': {'en': 'Pakistan', 'zh': '巴基斯坦'},
    'BJ': {'en': 'Benin', 'zh': '贝宁'},
    'ES': {'en': 'Spain', 'zh': '西班牙'},
    'GS': {'en': 'South Georgia and the South Sandwich Islands', 'zh': '南乔治亚岛和南桑威齐群岛'},
    'NI': {'en': 'Nicaragua', 'zh': '尼加拉瓜'},
    'SI': {'en': 'Slovenia', 'zh': '斯洛文尼亚'},
    'BH': {'en': 'Bahrain', 'zh': '巴林'},
    'IL': {'en': 'Israel', 'zh': '以色列'},
    'LA': {'en': 'Lao', 'zh': '老挝'},
    'CV': {'en': 'Cabo Verde', 'zh': '佛得角'},
    'PH': {'en': 'Philippines', 'zh': '菲律宾'},
    'GM': {'en': 'Gambia', 'zh': '冈比亚'},
    'TZ': {'en': 'Tanzania', 'zh': '坦桑尼亚'},
    'FR': {'en': 'France', 'zh': '法国'},
    'VE': {'en': 'Venezuela', 'zh': '委内瑞拉'},
    'QA': {'en': 'Qatar', 'zh': '卡塔尔'},
    'GH': {'en': 'Ghana', 'zh': '加纳'},
    'CC': {'en': 'Cocos [Keeling] Islands', 'zh': '科科斯群岛'},
    'RE': {'en': 'Reunion Island', 'zh': '留尼汪岛'},
    'UM': {'en': 'U.S. Minor Outlying Islands', 'zh': '美国边远小岛'},
    'NO': {'en': 'Norway', 'zh': '挪威'},
    'EH': {'en': 'Western Sahara', 'zh': '西撒哈拉'},
    'IO': {'en': 'British Indian Ocean Territory', 'zh': '英属印度洋领地'},
    'DK': {'en': 'Denmark', 'zh': '丹麦'},
    'IS': {'en': 'Iceland', 'zh': '冰岛'},
    'CO': {'en': 'Colombia', 'zh': '哥伦比亚'},
    'BY': {'en': 'Belarus', 'zh': '白俄罗斯'},
    'BA': {'en': 'Bosnia and Herzegovina', 'zh': '波黑'},
    'VI': {'en': 'United States Virgin Islands', 'zh': '美属维尔京群岛'},
    'KP': {'en': 'North Korea', 'zh': '朝鲜民主共和国'},
    'HT': {'en': 'Haiti', 'zh': '海地'},
    'MQ': {'en': 'Martinique', 'zh': '马提尼克'},
    'MR': {'en': 'Mauritania', 'zh': '毛里塔尼亚'},
    'RS': {'en': 'Serbia', 'zh': '塞尔维亚'},
    'YT': {'en': 'Mayotte', 'zh': '马约特'},
    'CH': {'en': 'Switzerland', 'zh': '瑞士'},
    'CM': {'en': 'Cameroon', 'zh': '喀麦隆'},
    'AW': {'en': 'Aruba', 'zh': '阿鲁巴'},
    'SE': {'en': 'Sweden', 'zh': '瑞典'},
    'SV': {'en': 'El Salvador', 'zh': '萨尔瓦多'},
    'BM': {'en': 'Bermuda', 'zh': '百慕大'},
    'CW': {'en': 'Curacao', 'zh': '库拉索'},
    'PE': {'en': 'Peru', 'zh': '秘鲁'},
    'AD': {'en': 'Andorra', 'zh': '安道尔'},
    'SZ': {'en': 'Swaziland', 'zh': '斯威士兰'},
    'PA': {'en': 'Panama', 'zh': '巴拿马'},
    'MN': {'en': 'Mongolia', 'zh': '蒙古'},
    'VC': {'en': 'Saint Vincent and the Grenadines', 'zh': '圣文森特和格林纳丁斯'},
    'TM': {'en': 'Turkmenistan', 'zh': '土库曼斯坦'}, 'SH': {'en': 'Saint Helena', 'zh': '圣赫勒拿'},
    'KH': {'en': 'Cambodia', 'zh': '柬埔寨'},
    'VG': {'en': 'British Virgin Islands', 'zh': '英属维尔京群岛'},
    'GE': {'en': 'Georgia', 'zh': '格鲁吉亚'},
    'CR': {'en': 'Costa Rica', 'zh': '哥斯达黎加'},
    'AM': {'en': 'Armenia', 'zh': '亚美尼亚'},
    'JM': {'en': 'Jamaica', 'zh': '牙买加'},
    'SB': {'en': 'Solomon Islands', 'zh': '所罗门群岛'},
    'UG': {'en': 'Uganda', 'zh': '乌干达'},
    'TF': {'en': 'French Southern Territories', 'zh': '法属南部领土'},
    'GB': {'en': 'United Kingdom', 'zh': '英国'},
    'WS': {'en': 'Samoa', 'zh': '萨摩亚'},
    'PF': {'en': 'French Polynesia', 'zh': '法属波利尼西亚'},
    'KY': {'en': 'Cayman Islands', 'zh': '开曼群岛'},
    'PY': {'en': 'Paraguay', 'zh': '巴拉圭'},
    'B1': {'en': '', 'zh': ''},
    'FO': {'en': 'Faroe Islands', 'zh': '法罗群岛'},
    'GA': {'en': 'Gabon', 'zh': '加蓬'}
}
